// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: internal/protobuf/proto/user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_internal_protobuf_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthId        string                 `protobuf:"bytes,2,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Name          *UserNameInfo          `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Contact       *UserContactInfo       `protobuf:"bytes,5,opt,name=contact,proto3" json:"contact,omitempty"`
	About         *UserAboutInfo         `protobuf:"bytes,6,opt,name=about,proto3" json:"about,omitempty"`
	Verification  *UserVerificationInfo  `protobuf:"bytes,7,opt,name=verification,proto3" json:"verification,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,8,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_internal_protobuf_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserResponse) GetAuthId() string {
	if x != nil {
		return x.AuthId
	}
	return ""
}

func (x *UserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserResponse) GetName() *UserNameInfo {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UserResponse) GetContact() *UserContactInfo {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *UserResponse) GetAbout() *UserAboutInfo {
	if x != nil {
		return x.About
	}
	return nil
}

func (x *UserResponse) GetVerification() *UserVerificationInfo {
	if x != nil {
		return x.Verification
	}
	return nil
}

func (x *UserResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UserNameInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserNameInfo) Reset() {
	*x = UserNameInfo{}
	mi := &file_internal_protobuf_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserNameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserNameInfo) ProtoMessage() {}

func (x *UserNameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserNameInfo.ProtoReflect.Descriptor instead.
func (*UserNameInfo) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserNameInfo) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserNameInfo) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type UserContactInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserContactInfo) Reset() {
	*x = UserContactInfo{}
	mi := &file_internal_protobuf_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserContactInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserContactInfo) ProtoMessage() {}

func (x *UserContactInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserContactInfo.ProtoReflect.Descriptor instead.
func (*UserContactInfo) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserContactInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserContactInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type UserAboutInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bio           string                 `protobuf:"bytes,1,opt,name=bio,proto3" json:"bio,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	BirthDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Gender        string                 `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAboutInfo) Reset() {
	*x = UserAboutInfo{}
	mi := &file_internal_protobuf_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAboutInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAboutInfo) ProtoMessage() {}

func (x *UserAboutInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAboutInfo.ProtoReflect.Descriptor instead.
func (*UserAboutInfo) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserAboutInfo) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserAboutInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UserAboutInfo) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *UserAboutInfo) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

type UserVerificationInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EmailVerifiedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=email_verified_at,json=emailVerifiedAt,proto3" json:"email_verified_at,omitempty"`
	PhoneVerifiedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=phone_verified_at,json=phoneVerifiedAt,proto3" json:"phone_verified_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserVerificationInfo) Reset() {
	*x = UserVerificationInfo{}
	mi := &file_internal_protobuf_proto_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserVerificationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserVerificationInfo) ProtoMessage() {}

func (x *UserVerificationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_proto_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserVerificationInfo.ProtoReflect.Descriptor instead.
func (*UserVerificationInfo) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserVerificationInfo) GetEmailVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EmailVerifiedAt
	}
	return nil
}

func (x *UserVerificationInfo) GetPhoneVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PhoneVerifiedAt
	}
	return nil
}

var File_internal_protobuf_proto_user_proto protoreflect.FileDescriptor

const file_internal_protobuf_proto_user_proto_rawDesc = "" +
	"\n" +
	"\"internal/protobuf/proto/user.proto\x12\x04user\x1a\x1fgoogle/protobuf/timestamp.proto\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xac\x03\n" +
	"\fUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\aauth_id\x18\x02 \x01(\tR\x06authId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12&\n" +
	"\x04name\x18\x04 \x01(\v2\x12.user.UserNameInfoR\x04name\x12/\n" +
	"\acontact\x18\x05 \x01(\v2\x15.user.UserContactInfoR\acontact\x12)\n" +
	"\x05about\x18\x06 \x01(\v2\x13.user.UserAboutInfoR\x05about\x12>\n" +
	"\fverification\x18\a \x01(\v2\x1a.user.UserVerificationInfoR\fverification\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\b \x01(\tR\tavatarUrl\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"J\n" +
	"\fUserNameInfo\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\"=\n" +
	"\x0fUserContactInfo\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\"\x96\x01\n" +
	"\rUserAboutInfo\x12\x10\n" +
	"\x03bio\x18\x01 \x01(\tR\x03bio\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"birth_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tbirthDate\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\tR\x06gender\"\xa6\x01\n" +
	"\x14UserVerificationInfo\x12F\n" +
	"\x11email_verified_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x0femailVerifiedAt\x12F\n" +
	"\x11phone_verified_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0fphoneVerifiedAt2F\n" +
	"\vUserService\x127\n" +
	"\vGetUserById\x12\x14.user.GetUserRequest\x1a\x12.user.UserResponseB\x05Z\x03/pbb\x06proto3"

var (
	file_internal_protobuf_proto_user_proto_rawDescOnce sync.Once
	file_internal_protobuf_proto_user_proto_rawDescData []byte
)

func file_internal_protobuf_proto_user_proto_rawDescGZIP() []byte {
	file_internal_protobuf_proto_user_proto_rawDescOnce.Do(func() {
		file_internal_protobuf_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protobuf_proto_user_proto_rawDesc), len(file_internal_protobuf_proto_user_proto_rawDesc)))
	})
	return file_internal_protobuf_proto_user_proto_rawDescData
}

var file_internal_protobuf_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_protobuf_proto_user_proto_goTypes = []any{
	(*GetUserRequest)(nil),        // 0: user.GetUserRequest
	(*UserResponse)(nil),          // 1: user.UserResponse
	(*UserNameInfo)(nil),          // 2: user.UserNameInfo
	(*UserContactInfo)(nil),       // 3: user.UserContactInfo
	(*UserAboutInfo)(nil),         // 4: user.UserAboutInfo
	(*UserVerificationInfo)(nil),  // 5: user.UserVerificationInfo
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_internal_protobuf_proto_user_proto_depIdxs = []int32{
	2,  // 0: user.UserResponse.name:type_name -> user.UserNameInfo
	3,  // 1: user.UserResponse.contact:type_name -> user.UserContactInfo
	4,  // 2: user.UserResponse.about:type_name -> user.UserAboutInfo
	5,  // 3: user.UserResponse.verification:type_name -> user.UserVerificationInfo
	6,  // 4: user.UserResponse.created_at:type_name -> google.protobuf.Timestamp
	6,  // 5: user.UserResponse.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 6: user.UserAboutInfo.birth_date:type_name -> google.protobuf.Timestamp
	6,  // 7: user.UserVerificationInfo.email_verified_at:type_name -> google.protobuf.Timestamp
	6,  // 8: user.UserVerificationInfo.phone_verified_at:type_name -> google.protobuf.Timestamp
	0,  // 9: user.UserService.GetUserById:input_type -> user.GetUserRequest
	1,  // 10: user.UserService.GetUserById:output_type -> user.UserResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_internal_protobuf_proto_user_proto_init() }
func file_internal_protobuf_proto_user_proto_init() {
	if File_internal_protobuf_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protobuf_proto_user_proto_rawDesc), len(file_internal_protobuf_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protobuf_proto_user_proto_goTypes,
		DependencyIndexes: file_internal_protobuf_proto_user_proto_depIdxs,
		MessageInfos:      file_internal_protobuf_proto_user_proto_msgTypes,
	}.Build()
	File_internal_protobuf_proto_user_proto = out.File
	file_internal_protobuf_proto_user_proto_goTypes = nil
	file_internal_protobuf_proto_user_proto_depIdxs = nil
}
